const clashData = {
  state: "inWar",
  teamSize: 45,
  attacksPerMember: 2,
  battleModifier: "none",
  preparationStartTime: "20251221T052647.000Z",
  startTime: "20251222T042647.000Z",
  endTime: "20251228T123200.000Z",
  clan: {
    tag: "#2UJLP22Y",
    name: "SWAT",
    badgeUrls: {
      small:
        "https://api-assets.clashofclans.com/badges/70/NeIjlTh56SrtcvBabMsZ1sf44phMW3oqWcvoIJnasAc.png",
      large:
        "https://api-assets.clashofclans.com/badges/512/NeIjlTh56SrtcvBabMsZ1sf44phMW3oqWcvoIJnasAc.png",
      medium:
        "https://api-assets.clashofclans.com/badges/200/NeIjlTh56SrtcvBabMsZ1sf44phMW3oqWcvoIJnasAc.png",
    },
    clanLevel: 33,
    attacks: 65,
    stars: 134,
    destructionPercentage: 99.86667,
    members: [
      {
        tag: "#P0RGRJR8",
        name: "Boddah 121",
        townhallLevel: 18,
        mapPosition: 35,
        attacks: [
          {
            attackerTag: "#P0RGRJR8",
            defenderTag: "#908V22VGL",
            stars: 3,
            destructionPercentage: 100,
            order: 138,
            duration: 131,
          },
          {
            attackerTag: "#P0RGRJR8",
            defenderTag: "#2VUGPU9G",
            stars: 3,
            destructionPercentage: 100,
            order: 139,
            duration: 118,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#2CPY9UVP",
          defenderTag: "#P0RGRJR8",
          stars: 3,
          destructionPercentage: 100,
          order: 76,
          duration: 169,
        },
      },
      {
        tag: "#P9JVJC2L",
        name: "davizao",
        townhallLevel: 18,
        mapPosition: 40,
        attacks: [
          {
            attackerTag: "#P9JVJC2L",
            defenderTag: "#9YGJ9LUPP",
            stars: 3,
            destructionPercentage: 100,
            order: 30,
            duration: 145,
          },
          {
            attackerTag: "#P9JVJC2L",
            defenderTag: "#9J9UVP900",
            stars: 2,
            destructionPercentage: 99,
            order: 31,
            duration: 180,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#LP02PV8V",
          defenderTag: "#P9JVJC2L",
          stars: 3,
          destructionPercentage: 100,
          order: 44,
          duration: 142,
        },
      },
      {
        tag: "#GVJVGC0P",
        name: "⚜️⚔️KBLIM⚔️⚜️",
        townhallLevel: 18,
        mapPosition: 24,
        attacks: [
          {
            attackerTag: "#GVJVGC0P",
            defenderTag: "#R9R99QLC",
            stars: 2,
            destructionPercentage: 88,
            order: 83,
            duration: 180,
          },
          {
            attackerTag: "#GVJVGC0P",
            defenderTag: "#LP02PV8V",
            stars: 2,
            destructionPercentage: 91,
            order: 84,
            duration: 174,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#LQ2V0CQ8",
          defenderTag: "#GVJVGC0P",
          stars: 3,
          destructionPercentage: 100,
          order: 98,
          duration: 172,
        },
      },
      {
        tag: "#RC2U2YJR",
        name: "♠️War Machine♠️",
        townhallLevel: 18,
        mapPosition: 31,
        attacks: [
          {
            attackerTag: "#RC2U2YJR",
            defenderTag: "#20UJCPL2C",
            stars: 3,
            destructionPercentage: 100,
            order: 127,
            duration: 145,
          },
          {
            attackerTag: "#RC2U2YJR",
            defenderTag: "#98GQ022RP",
            stars: 3,
            destructionPercentage: 100,
            order: 130,
            duration: 136,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#28GC2L8C9",
          defenderTag: "#RC2U2YJR",
          stars: 3,
          destructionPercentage: 100,
          order: 62,
          duration: 87,
        },
      },
      {
        tag: "#PGVCLPJG",
        name: "BLACKWATER",
        townhallLevel: 18,
        mapPosition: 42,
        attacks: [
          {
            attackerTag: "#PGVCLPJG",
            defenderTag: "#2ULYQPCGV",
            stars: 3,
            destructionPercentage: 100,
            order: 19,
            duration: 147,
          },
          {
            attackerTag: "#PGVCLPJG",
            defenderTag: "#2QG9UP828",
            stars: 1,
            destructionPercentage: 89,
            order: 85,
            duration: 149,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#2JCCU8YUC",
          defenderTag: "#PGVCLPJG",
          stars: 3,
          destructionPercentage: 100,
          order: 77,
          duration: 101,
        },
      },
      {
        tag: "#QPP92V90",
        name: "renan",
        townhallLevel: 18,
        mapPosition: 25,
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#PVRJCC99",
          defenderTag: "#QPP92V90",
          stars: 3,
          destructionPercentage: 100,
          order: 38,
          duration: 98,
        },
      },
      {
        tag: "#29JPLJQCP",
        name: "Ysllan ❤️❤️",
        townhallLevel: 18,
        mapPosition: 32,
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#9RUCVQQVR",
          defenderTag: "#29JPLJQCP",
          stars: 3,
          destructionPercentage: 100,
          order: 65,
          duration: 152,
        },
      },
      {
        tag: "#2RQJU0RQG",
        name: "ʟᴀɴᴄᴇʟᴏᴛ",
        townhallLevel: 18,
        mapPosition: 27,
        attacks: [
          {
            attackerTag: "#2RQJU0RQG",
            defenderTag: "#QVGGJC9R",
            stars: 3,
            destructionPercentage: 100,
            order: 91,
            duration: 146,
          },
          {
            attackerTag: "#2RQJU0RQG",
            defenderTag: "#PVRJCC99",
            stars: 3,
            destructionPercentage: 100,
            order: 140,
            duration: 156,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#LRPJCYL0J",
          defenderTag: "#2RQJU0RQG",
          stars: 3,
          destructionPercentage: 100,
          order: 59,
          duration: 166,
        },
      },
      {
        tag: "#PV0UVVR08",
        name: "Schopenhauer",
        townhallLevel: 18,
        mapPosition: 21,
        attacks: [
          {
            attackerTag: "#PV0UVVR08",
            defenderTag: "#2JCCU8YUC",
            stars: 3,
            destructionPercentage: 100,
            order: 92,
            duration: 174,
          },
          {
            attackerTag: "#PV0UVVR08",
            defenderTag: "#UG92YL99",
            stars: 3,
            destructionPercentage: 100,
            order: 110,
            duration: 153,
          },
        ],
        opponentAttacks: 3,
        bestOpponentAttack: {
          attackerTag: "#LQ2V0CQ8",
          defenderTag: "#PV0UVVR08",
          stars: 3,
          destructionPercentage: 100,
          order: 97,
          duration: 164,
        },
      },
      {
        tag: "#Q9CPG8JV2",
        name: "FERRARI",
        townhallLevel: 18,
        mapPosition: 15,
        attacks: [
          {
            attackerTag: "#Q9CPG8JV2",
            defenderTag: "#GUUCJVV0",
            stars: 3,
            destructionPercentage: 100,
            order: 57,
            duration: 170,
          },
          {
            attackerTag: "#Q9CPG8JV2",
            defenderTag: "#28GC2L8C9",
            stars: 3,
            destructionPercentage: 100,
            order: 58,
            duration: 149,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#289QVP0U2",
          defenderTag: "#Q9CPG8JV2",
          stars: 3,
          destructionPercentage: 100,
          order: 39,
          duration: 154,
        },
      },
      {
        tag: "#92P9PJVJ0",
        name: "SWT WIN",
        townhallLevel: 18,
        mapPosition: 16,
        attacks: [
          {
            attackerTag: "#92P9PJVJ0",
            defenderTag: "#2VUGPU9G",
            stars: 2,
            destructionPercentage: 99,
            order: 128,
            duration: 180,
          },
          {
            attackerTag: "#92P9PJVJ0",
            defenderTag: "#PGVJL0QG2",
            stars: 3,
            destructionPercentage: 100,
            order: 132,
            duration: 173,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#PGVJL0QG2",
          defenderTag: "#92P9PJVJ0",
          stars: 3,
          destructionPercentage: 100,
          order: 5,
          duration: 162,
        },
      },
      {
        tag: "#VV0VLJJ0",
        name: "DoWn NoOb™",
        townhallLevel: 18,
        mapPosition: 36,
        attacks: [
          {
            attackerTag: "#VV0VLJJ0",
            defenderTag: "#8YUVULJCV",
            stars: 3,
            destructionPercentage: 100,
            order: 104,
            duration: 156,
          },
          {
            attackerTag: "#VV0VLJJ0",
            defenderTag: "#LP02PV8V",
            stars: 2,
            destructionPercentage: 99,
            order: 105,
            duration: 178,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#UG92YL99",
          defenderTag: "#VV0VLJJ0",
          stars: 3,
          destructionPercentage: 100,
          order: 49,
          duration: 154,
        },
      },
      {
        tag: "#8L8JL90YR",
        name: "SWT no face",
        townhallLevel: 18,
        mapPosition: 38,
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#8YUVULJCV",
          defenderTag: "#8L8JL90YR",
          stars: 3,
          destructionPercentage: 100,
          order: 103,
          duration: 134,
        },
      },
      {
        tag: "#P9C2VRJ0R",
        name: "Duran ❤️ A",
        townhallLevel: 18,
        mapPosition: 19,
        attacks: [
          {
            attackerTag: "#P9C2VRJ0R",
            defenderTag: "#2808YP02Y",
            stars: 3,
            destructionPercentage: 100,
            order: 63,
            duration: 115,
          },
          {
            attackerTag: "#P9C2VRJ0R",
            defenderTag: "#2L8RCV88V",
            stars: 3,
            destructionPercentage: 100,
            order: 64,
            duration: 131,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#GUUCJVV0",
          defenderTag: "#P9C2VRJ0R",
          stars: 3,
          destructionPercentage: 100,
          order: 96,
          duration: 153,
        },
      },
      {
        tag: "#998V9YJYP",
        name: "baws",
        townhallLevel: 18,
        mapPosition: 9,
        opponentAttacks: 6,
        bestOpponentAttack: {
          attackerTag: "#9Y820G0GU",
          defenderTag: "#998V9YJYP",
          stars: 3,
          destructionPercentage: 100,
          order: 116,
          duration: 153,
        },
      },
      {
        tag: "#Q8LCQL2GG",
        name: "Hybrid",
        townhallLevel: 18,
        mapPosition: 28,
        attacks: [
          {
            attackerTag: "#Q8LCQL2GG",
            defenderTag: "#89JP8QVJQ",
            stars: 3,
            destructionPercentage: 100,
            order: 111,
            duration: 165,
          },
          {
            attackerTag: "#Q8LCQL2GG",
            defenderTag: "#PGVJL0QG2",
            stars: 2,
            destructionPercentage: 95,
            order: 112,
            duration: 180,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#28GC2L8C9",
          defenderTag: "#Q8LCQL2GG",
          stars: 3,
          destructionPercentage: 100,
          order: 60,
          duration: 101,
        },
      },
      {
        tag: "#UY2QUUVQ",
        name: "RIKE☣️",
        townhallLevel: 18,
        mapPosition: 8,
        attacks: [
          {
            attackerTag: "#UY2QUUVQ",
            defenderTag: "#9GCLY8YU8",
            stars: 3,
            destructionPercentage: 100,
            order: 67,
            duration: 147,
          },
          {
            attackerTag: "#UY2QUUVQ",
            defenderTag: "#Y9LC2VLQP",
            stars: 3,
            destructionPercentage: 100,
            order: 68,
            duration: 161,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#929GQ92CJ",
          defenderTag: "#UY2QUUVQ",
          stars: 3,
          destructionPercentage: 100,
          order: 36,
          duration: 88,
        },
      },
      {
        tag: "#282RCCLQ",
        name: "√ﾉ刀ﾉᄃﾉひ丂 ﾉ√",
        townhallLevel: 17,
        mapPosition: 45,
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#2JCCU8YUC",
          defenderTag: "#282RCCLQ",
          stars: 3,
          destructionPercentage: 100,
          order: 79,
          duration: 76,
        },
      },
      {
        tag: "#QP90YQ8R2",
        name: "Karma",
        townhallLevel: 18,
        mapPosition: 5,
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#Y9LC2VLQP",
          defenderTag: "#QP90YQ8R2",
          stars: 3,
          destructionPercentage: 100,
          order: 4,
          duration: 166,
        },
      },
      {
        tag: "#9GG0Y9L28",
        name: "SWT ALUCARD",
        townhallLevel: 18,
        mapPosition: 12,
        attacks: [
          {
            attackerTag: "#9GG0Y9L28",
            defenderTag: "#RV82802U",
            stars: 3,
            destructionPercentage: 100,
            order: 52,
            duration: 158,
          },
          {
            attackerTag: "#9GG0Y9L28",
            defenderTag: "#289QVP0U2",
            stars: 3,
            destructionPercentage: 100,
            order: 53,
            duration: 135,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#289QVP0U2",
          defenderTag: "#9GG0Y9L28",
          stars: 3,
          destructionPercentage: 100,
          order: 37,
          duration: 175,
        },
      },
      {
        tag: "#80JYQVYCC",
        name: "iN_Following",
        townhallLevel: 18,
        mapPosition: 33,
        attacks: [
          {
            attackerTag: "#80JYQVYCC",
            defenderTag: "#929GQ92CJ",
            stars: 3,
            destructionPercentage: 100,
            order: 99,
            duration: 141,
          },
          {
            attackerTag: "#80JYQVYCC",
            defenderTag: "#YV2L92YYQ",
            stars: 3,
            destructionPercentage: 100,
            order: 100,
            duration: 149,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#89JP8QVJQ",
          defenderTag: "#80JYQVYCC",
          stars: 3,
          destructionPercentage: 100,
          order: 73,
          duration: 152,
        },
      },
      {
        tag: "#8G2JRLJL",
        name: "Jordan",
        townhallLevel: 18,
        mapPosition: 39,
        attacks: [
          {
            attackerTag: "#8G2JRLJL",
            defenderTag: "#2299G8G2U",
            stars: 3,
            destructionPercentage: 100,
            order: 48,
            duration: 154,
          },
          {
            attackerTag: "#8G2JRLJL",
            defenderTag: "#LRPJCYL0J",
            stars: 3,
            destructionPercentage: 100,
            order: 66,
            duration: 159,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#80QQGGCV0",
          defenderTag: "#8G2JRLJL",
          stars: 3,
          destructionPercentage: 100,
          order: 102,
          duration: 170,
        },
      },
      {
        tag: "#222VJ9LCR",
        name: "Dinas❌tia",
        townhallLevel: 18,
        mapPosition: 41,
        attacks: [
          {
            attackerTag: "#222VJ9LCR",
            defenderTag: "#2LCJP9VU",
            stars: 3,
            destructionPercentage: 100,
            order: 107,
            duration: 151,
          },
          {
            attackerTag: "#222VJ9LCR",
            defenderTag: "#UGJCUGP",
            stars: 3,
            destructionPercentage: 100,
            order: 108,
            duration: 154,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#UG92YL99",
          defenderTag: "#222VJ9LCR",
          stars: 3,
          destructionPercentage: 100,
          order: 32,
          duration: 172,
        },
      },
      {
        tag: "#20PGJPVUC",
        name: "Renan C.",
        townhallLevel: 18,
        mapPosition: 43,
        opponentAttacks: 3,
        bestOpponentAttack: {
          attackerTag: "#UGJCUGP",
          defenderTag: "#20PGJPVUC",
          stars: 3,
          destructionPercentage: 100,
          order: 119,
          duration: 115,
        },
      },
      {
        tag: "#2LY829CC",
        name: "Bruno",
        townhallLevel: 18,
        mapPosition: 18,
        attacks: [
          {
            attackerTag: "#2LY829CC",
            defenderTag: "#L9RP8L8Q",
            stars: 3,
            destructionPercentage: 100,
            order: 72,
            duration: 130,
          },
          {
            attackerTag: "#2LY829CC",
            defenderTag: "#8PCL02PY",
            stars: 3,
            destructionPercentage: 100,
            order: 74,
            duration: 144,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#L9RP8L8Q",
          defenderTag: "#2LY829CC",
          stars: 3,
          destructionPercentage: 100,
          order: 24,
          duration: 129,
        },
      },
      {
        tag: "#29LY9G2P",
        name: "The Fodz Vegeta",
        townhallLevel: 18,
        mapPosition: 4,
        attacks: [
          {
            attackerTag: "#29LY9G2P",
            defenderTag: "#2VRVQ9QG",
            stars: 3,
            destructionPercentage: 100,
            order: 16,
            duration: 159,
          },
          {
            attackerTag: "#29LY9G2P",
            defenderTag: "#LQ2V0CQ8",
            stars: 2,
            destructionPercentage: 88,
            order: 17,
            duration: 180,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#QUL8Q0VUU",
          defenderTag: "#29LY9G2P",
          stars: 3,
          destructionPercentage: 100,
          order: 21,
          duration: 176,
        },
      },
      {
        tag: "#VGUG90RY",
        name: "Malo❌keiro",
        townhallLevel: 18,
        mapPosition: 22,
        attacks: [
          {
            attackerTag: "#VGUG90RY",
            defenderTag: "#8RL0V8JPY",
            stars: 3,
            destructionPercentage: 100,
            order: 93,
            duration: 165,
          },
          {
            attackerTag: "#VGUG90RY",
            defenderTag: "#2QG9UP828",
            stars: 3,
            destructionPercentage: 100,
            order: 109,
            duration: 121,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#9YGJ9LUPP",
          defenderTag: "#VGUG90RY",
          stars: 3,
          destructionPercentage: 100,
          order: 33,
          duration: 179,
        },
      },
      {
        tag: "#8LUGPRRJY",
        name: "Lv.36ㅤVenom™",
        townhallLevel: 18,
        mapPosition: 6,
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#2VRVQ9QG",
          defenderTag: "#8LUGPRRJY",
          stars: 3,
          destructionPercentage: 100,
          order: 13,
          duration: 176,
        },
      },
      {
        tag: "#YG9Q8G20",
        name: "⭐MEGA 2⭐",
        townhallLevel: 18,
        mapPosition: 14,
        opponentAttacks: 3,
        bestOpponentAttack: {
          attackerTag: "#UGJVP9GG",
          defenderTag: "#YG9Q8G20",
          stars: 3,
          destructionPercentage: 100,
          order: 90,
          duration: 167,
        },
      },
      {
        tag: "#GQ0RR2PGL",
        name: "⭐MTS™⭐",
        townhallLevel: 18,
        mapPosition: 11,
        attacks: [
          {
            attackerTag: "#GQ0RR2PGL",
            defenderTag: "#R9R99QLC",
            stars: 1,
            destructionPercentage: 70,
            order: 80,
            duration: 152,
          },
          {
            attackerTag: "#GQ0RR2PGL",
            defenderTag: "#8RL0V8JPY",
            stars: 2,
            destructionPercentage: 83,
            order: 82,
            duration: 170,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#UGJVP9GG",
          defenderTag: "#GQ0RR2PGL",
          stars: 3,
          destructionPercentage: 100,
          order: 88,
          duration: 131,
        },
      },
      {
        tag: "#8U929CVRL",
        name: "Bruno Alucard",
        townhallLevel: 18,
        mapPosition: 20,
        attacks: [
          {
            attackerTag: "#8U929CVRL",
            defenderTag: "#L0GPVGYG",
            stars: 2,
            destructionPercentage: 94,
            order: 141,
            duration: 180,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#L9RP8L8Q",
          defenderTag: "#8U929CVRL",
          stars: 3,
          destructionPercentage: 100,
          order: 23,
          duration: 139,
        },
      },
      {
        tag: "#2R2YGUCRG",
        name: "Lucas Kilian",
        townhallLevel: 18,
        mapPosition: 37,
        attacks: [
          {
            attackerTag: "#2R2YGUCRG",
            defenderTag: "#PVRJCC99",
            stars: 1,
            destructionPercentage: 98,
            order: 125,
            duration: 180,
          },
          {
            attackerTag: "#2R2YGUCRG",
            defenderTag: "#UGJVP9GG",
            stars: 3,
            destructionPercentage: 100,
            order: 126,
            duration: 174,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#9J9UVP900",
          defenderTag: "#2R2YGUCRG",
          stars: 3,
          destructionPercentage: 100,
          order: 75,
          duration: 89,
        },
      },
      {
        tag: "#YQULYPYQU",
        name: "伝説 Royal Madson",
        townhallLevel: 18,
        mapPosition: 13,
        attacks: [
          {
            attackerTag: "#YQULYPYQU",
            defenderTag: "#LP02PV8V",
            stars: 3,
            destructionPercentage: 100,
            order: 114,
            duration: 157,
          },
          {
            attackerTag: "#YQULYPYQU",
            defenderTag: "#YP9PGYGVQ",
            stars: 3,
            destructionPercentage: 100,
            order: 115,
            duration: 149,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#9GCLY8YU8",
          defenderTag: "#YQULYPYQU",
          stars: 3,
          destructionPercentage: 100,
          order: 41,
          duration: 163,
        },
      },
      {
        tag: "#LGCRRRRCU",
        name: "Gwyn",
        townhallLevel: 18,
        mapPosition: 34,
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#89JP8QVJQ",
          defenderTag: "#LGCRRRRCU",
          stars: 3,
          destructionPercentage: 100,
          order: 71,
          duration: 176,
        },
      },
      {
        tag: "#89YUGUQQ",
        name: "marrento",
        townhallLevel: 18,
        mapPosition: 30,
        attacks: [
          {
            attackerTag: "#89YUGUQQ",
            defenderTag: "#80QQGGCV0",
            stars: 3,
            destructionPercentage: 100,
            order: 136,
            duration: 140,
          },
          {
            attackerTag: "#89YUGUQQ",
            defenderTag: "#9Y820G0GU",
            stars: 3,
            destructionPercentage: 100,
            order: 137,
            duration: 142,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#9RUCVQQVR",
          defenderTag: "#89YUGUQQ",
          stars: 3,
          destructionPercentage: 100,
          order: 61,
          duration: 133,
        },
      },
      {
        tag: "#P8CYY2QV",
        name: "SWT SkyLord",
        townhallLevel: 18,
        mapPosition: 17,
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#98GQ022RP",
          defenderTag: "#P8CYY2QV",
          stars: 3,
          destructionPercentage: 100,
          order: 54,
          duration: 178,
        },
      },
      {
        tag: "#YPLPJ0QPQ",
        name: "SWT Raymond",
        townhallLevel: 18,
        mapPosition: 10,
        attacks: [
          {
            attackerTag: "#YPLPJ0QPQ",
            defenderTag: "#PGVJL0QG2",
            stars: 1,
            destructionPercentage: 62,
            order: 129,
            duration: 146,
          },
          {
            attackerTag: "#YPLPJ0QPQ",
            defenderTag: "#L0GPVGYG",
            stars: 2,
            destructionPercentage: 87,
            order: 131,
            duration: 152,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#2VRVQ9QG",
          defenderTag: "#YPLPJ0QPQ",
          stars: 3,
          destructionPercentage: 100,
          order: 10,
          duration: 141,
        },
      },
      {
        tag: "#2J9VJ8V80",
        name: "Rafaela",
        townhallLevel: 18,
        mapPosition: 26,
        attacks: [
          {
            attackerTag: "#2J9VJ8V80",
            defenderTag: "#2CPY9UVP",
            stars: 3,
            destructionPercentage: 100,
            order: 45,
            duration: 141,
          },
          {
            attackerTag: "#2J9VJ8V80",
            defenderTag: "#289QVP0U2",
            stars: 2,
            destructionPercentage: 93,
            order: 50,
            duration: 172,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#9GCLY8YU8",
          defenderTag: "#2J9VJ8V80",
          stars: 3,
          destructionPercentage: 100,
          order: 42,
          duration: 126,
        },
      },
      {
        tag: "#LC0PQ202J",
        name: "Taro Sakamoto〆",
        townhallLevel: 18,
        mapPosition: 29,
        attacks: [
          {
            attackerTag: "#LC0PQ202J",
            defenderTag: "#QUL8Q0VUU",
            stars: 3,
            destructionPercentage: 100,
            order: 14,
            duration: 161,
          },
          {
            attackerTag: "#LC0PQ202J",
            defenderTag: "#2GC9QVYPL",
            stars: 3,
            destructionPercentage: 100,
            order: 15,
            duration: 174,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#2ULYQPCGV",
          defenderTag: "#LC0PQ202J",
          stars: 3,
          destructionPercentage: 100,
          order: 25,
          duration: 148,
        },
      },
      {
        tag: "#LQLPC002Q",
        name: "Davi",
        townhallLevel: 18,
        mapPosition: 23,
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#LRPJCYL0J",
          defenderTag: "#LQLPC002Q",
          stars: 3,
          destructionPercentage: 100,
          order: 56,
          duration: 136,
        },
      },
      {
        tag: "#UCPC8R0L",
        name: "BeBuNz 01",
        townhallLevel: 18,
        mapPosition: 1,
        attacks: [
          {
            attackerTag: "#UCPC8R0L",
            defenderTag: "#9RUCVQQVR",
            stars: 3,
            destructionPercentage: 100,
            order: 43,
            duration: 159,
          },
          {
            attackerTag: "#UCPC8R0L",
            defenderTag: "#RV82802U",
            stars: 1,
            destructionPercentage: 91,
            order: 47,
            duration: 163,
          },
        ],
        opponentAttacks: 6,
        bestOpponentAttack: {
          attackerTag: "#8PCL02PY",
          defenderTag: "#UCPC8R0L",
          stars: 3,
          destructionPercentage: 100,
          order: 1,
          duration: 169,
        },
      },
      {
        tag: "#CC9J9GRG",
        name: "Guilherme",
        townhallLevel: 18,
        mapPosition: 2,
        attacks: [
          {
            attackerTag: "#CC9J9GRG",
            defenderTag: "#8RL0V8JPY",
            stars: 2,
            destructionPercentage: 99,
            order: 89,
            duration: 180,
          },
          {
            attackerTag: "#CC9J9GRG",
            defenderTag: "#9J9UVP900",
            stars: 3,
            destructionPercentage: 100,
            order: 95,
            duration: 164,
          },
        ],
        opponentAttacks: 4,
        bestOpponentAttack: {
          attackerTag: "#2808YP02Y",
          defenderTag: "#CC9J9GRG",
          stars: 3,
          destructionPercentage: 100,
          order: 12,
          duration: 118,
        },
      },
      {
        tag: "#29898CL2Q",
        name: "Héli0zin",
        townhallLevel: 18,
        mapPosition: 44,
        attacks: [
          {
            attackerTag: "#29898CL2Q",
            defenderTag: "#R9R99QLC",
            stars: 3,
            destructionPercentage: 100,
            order: 86,
            duration: 152,
          },
          {
            attackerTag: "#29898CL2Q",
            defenderTag: "#8YUVULJCV",
            stars: 2,
            destructionPercentage: 90,
            order: 87,
            duration: 180,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#9J9UVP900",
          defenderTag: "#29898CL2Q",
          stars: 3,
          destructionPercentage: 100,
          order: 78,
          duration: 112,
        },
      },
      {
        tag: "#2CC0VRUCL",
        name: "SWT EVERTON",
        townhallLevel: 18,
        mapPosition: 7,
        attacks: [
          {
            attackerTag: "#2CC0VRUCL",
            defenderTag: "#98GQ022RP",
            stars: 2,
            destructionPercentage: 81,
            order: 117,
            duration: 180,
          },
          {
            attackerTag: "#2CC0VRUCL",
            defenderTag: "#908V22VGL",
            stars: 2,
            destructionPercentage: 99,
            order: 118,
            duration: 180,
          },
        ],
        opponentAttacks: 3,
        bestOpponentAttack: {
          attackerTag: "#929GQ92CJ",
          defenderTag: "#2CC0VRUCL",
          stars: 3,
          destructionPercentage: 100,
          order: 35,
          duration: 129,
        },
      },
      {
        tag: "#YJUY2GCVQ",
        name: "GURI",
        townhallLevel: 18,
        mapPosition: 3,
        attacks: [
          {
            attackerTag: "#YJUY2GCVQ",
            defenderTag: "#LQ2V0CQ8",
            stars: 3,
            destructionPercentage: 100,
            order: 28,
            duration: 165,
          },
          {
            attackerTag: "#YJUY2GCVQ",
            defenderTag: "#RV82802U",
            stars: 2,
            destructionPercentage: 91,
            order: 29,
            duration: 180,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#2808YP02Y",
          defenderTag: "#YJUY2GCVQ",
          stars: 3,
          destructionPercentage: 100,
          order: 7,
          duration: 163,
        },
      },
    ],
  },
  opponent: {
    tag: "#2LQCL92UL",
    name: '"NORMAL" Clan',
    badgeUrls: {
      small:
        "https://api-assets.clashofclans.com/badges/70/5xfl6rc_5T7vo3VCykkbi1uDR2D-Un7xSJHuLdRweFY.png",
      large:
        "https://api-assets.clashofclans.com/badges/512/5xfl6rc_5T7vo3VCykkbi1uDR2D-Un7xSJHuLdRweFY.png",
      medium:
        "https://api-assets.clashofclans.com/badges/200/5xfl6rc_5T7vo3VCykkbi1uDR2D-Un7xSJHuLdRweFY.png",
    },
    clanLevel: 25,
    attacks: 76,
    stars: 135,
    destructionPercentage: 100,
    members: [
      {
        tag: "#8PCL02PY",
        name: "ch1ste",
        townhallLevel: 18,
        mapPosition: 22,
        attacks: [
          {
            attackerTag: "#8PCL02PY",
            defenderTag: "#UCPC8R0L",
            stars: 3,
            destructionPercentage: 100,
            order: 1,
            duration: 169,
          },
          {
            attackerTag: "#8PCL02PY",
            defenderTag: "#CC9J9GRG",
            stars: 2,
            destructionPercentage: 98,
            order: 3,
            duration: 180,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#2LY829CC",
          defenderTag: "#8PCL02PY",
          stars: 3,
          destructionPercentage: 100,
          order: 74,
          duration: 144,
        },
      },
      {
        tag: "#20UJCPL2C",
        name: "DZ Zomboy™",
        townhallLevel: 18,
        mapPosition: 44,
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#RC2U2YJR",
          defenderTag: "#20UJCPL2C",
          stars: 3,
          destructionPercentage: 100,
          order: 127,
          duration: 145,
        },
      },
      {
        tag: "#2VUGPU9G",
        name: "DEPRESSED KID雨",
        townhallLevel: 18,
        mapPosition: 39,
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#P0RGRJR8",
          defenderTag: "#2VUGPU9G",
          stars: 3,
          destructionPercentage: 100,
          order: 139,
          duration: 118,
        },
      },
      {
        tag: "#2808YP02Y",
        name: "THE LEGEND",
        townhallLevel: 18,
        mapPosition: 13,
        attacks: [
          {
            attackerTag: "#2808YP02Y",
            defenderTag: "#YJUY2GCVQ",
            stars: 3,
            destructionPercentage: 100,
            order: 7,
            duration: 163,
          },
          {
            attackerTag: "#2808YP02Y",
            defenderTag: "#CC9J9GRG",
            stars: 3,
            destructionPercentage: 100,
            order: 12,
            duration: 118,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#P9C2VRJ0R",
          defenderTag: "#2808YP02Y",
          stars: 3,
          destructionPercentage: 100,
          order: 63,
          duration: 115,
        },
      },
      {
        tag: "#L0GPVGYG",
        name: "Jose Cuervo",
        townhallLevel: 18,
        mapPosition: 40,
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#8U929CVRL",
          defenderTag: "#L0GPVGYG",
          stars: 2,
          destructionPercentage: 94,
          order: 141,
          duration: 180,
        },
      },
      {
        tag: "#Y9LC2VLQP",
        name: "“NRMAL” ✩★MAX★✩",
        townhallLevel: 18,
        mapPosition: 16,
        attacks: [
          {
            attackerTag: "#Y9LC2VLQP",
            defenderTag: "#QP90YQ8R2",
            stars: 3,
            destructionPercentage: 100,
            order: 4,
            duration: 166,
          },
          {
            attackerTag: "#Y9LC2VLQP",
            defenderTag: "#2CC0VRUCL",
            stars: 2,
            destructionPercentage: 93,
            order: 9,
            duration: 180,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#UY2QUUVQ",
          defenderTag: "#Y9LC2VLQP",
          stars: 3,
          destructionPercentage: 100,
          order: 68,
          duration: 161,
        },
      },
      {
        tag: "#YV2L92YYQ",
        name: "ValentínRios22",
        townhallLevel: 18,
        mapPosition: 29,
        attacks: [
          {
            attackerTag: "#YV2L92YYQ",
            defenderTag: "#8L8JL90YR",
            stars: 2,
            destructionPercentage: 73,
            order: 81,
            duration: 92,
          },
          {
            attackerTag: "#YV2L92YYQ",
            defenderTag: "#UCPC8R0L",
            stars: 2,
            destructionPercentage: 94,
            order: 123,
            duration: 180,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#80JYQVYCC",
          defenderTag: "#YV2L92YYQ",
          stars: 3,
          destructionPercentage: 100,
          order: 100,
          duration: 149,
        },
      },
      {
        tag: "#GUUCJVV0",
        name: "Ranger77 :)",
        townhallLevel: 18,
        mapPosition: 10,
        attacks: [
          {
            attackerTag: "#GUUCJVV0",
            defenderTag: "#998V9YJYP",
            stars: 0,
            destructionPercentage: 4,
            order: 94,
            duration: 17,
          },
          {
            attackerTag: "#GUUCJVV0",
            defenderTag: "#P9C2VRJ0R",
            stars: 3,
            destructionPercentage: 100,
            order: 96,
            duration: 153,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#Q9CPG8JV2",
          defenderTag: "#GUUCJVV0",
          stars: 3,
          destructionPercentage: 100,
          order: 57,
          duration: 170,
        },
      },
      {
        tag: "#2299G8G2U",
        name: "NRML MRKSMNBBY",
        townhallLevel: 18,
        mapPosition: 12,
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#8G2JRLJL",
          defenderTag: "#2299G8G2U",
          stars: 3,
          destructionPercentage: 100,
          order: 48,
          duration: 154,
        },
      },
      {
        tag: "#L9RP8L8Q",
        name: ">>_Carlos_<<",
        townhallLevel: 18,
        mapPosition: 20,
        attacks: [
          {
            attackerTag: "#L9RP8L8Q",
            defenderTag: "#8U929CVRL",
            stars: 3,
            destructionPercentage: 100,
            order: 23,
            duration: 139,
          },
          {
            attackerTag: "#L9RP8L8Q",
            defenderTag: "#2LY829CC",
            stars: 3,
            destructionPercentage: 100,
            order: 24,
            duration: 129,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#2LY829CC",
          defenderTag: "#L9RP8L8Q",
          stars: 3,
          destructionPercentage: 100,
          order: 72,
          duration: 130,
        },
      },
      {
        tag: "#LP02PV8V",
        name: "Sharped",
        townhallLevel: 18,
        mapPosition: 24,
        attacks: [
          {
            attackerTag: "#LP02PV8V",
            defenderTag: "#P9JVJC2L",
            stars: 3,
            destructionPercentage: 100,
            order: 44,
            duration: 142,
          },
          {
            attackerTag: "#LP02PV8V",
            defenderTag: "#8G2JRLJL",
            stars: 2,
            destructionPercentage: 94,
            order: 46,
            duration: 173,
          },
        ],
        opponentAttacks: 3,
        bestOpponentAttack: {
          attackerTag: "#YQULYPYQU",
          defenderTag: "#LP02PV8V",
          stars: 3,
          destructionPercentage: 100,
          order: 114,
          duration: 157,
        },
      },
      {
        tag: "#UG92YL99",
        name: "CARRIER",
        townhallLevel: 18,
        mapPosition: 30,
        attacks: [
          {
            attackerTag: "#UG92YL99",
            defenderTag: "#222VJ9LCR",
            stars: 3,
            destructionPercentage: 100,
            order: 32,
            duration: 172,
          },
          {
            attackerTag: "#UG92YL99",
            defenderTag: "#VV0VLJJ0",
            stars: 3,
            destructionPercentage: 100,
            order: 49,
            duration: 154,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#PV0UVVR08",
          defenderTag: "#UG92YL99",
          stars: 3,
          destructionPercentage: 100,
          order: 110,
          duration: 153,
        },
      },
      {
        tag: "#QVGGJC9R",
        name: "FcoReyes",
        townhallLevel: 18,
        mapPosition: 26,
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#2RQJU0RQG",
          defenderTag: "#QVGGJC9R",
          stars: 3,
          destructionPercentage: 100,
          order: 91,
          duration: 146,
        },
      },
      {
        tag: "#908V22VGL",
        name: "《☆CAMILO ☆》",
        townhallLevel: 18,
        mapPosition: 38,
        attacks: [
          {
            attackerTag: "#908V22VGL",
            defenderTag: "#UCPC8R0L",
            stars: 1,
            destructionPercentage: 24,
            order: 134,
            duration: 29,
          },
          {
            attackerTag: "#908V22VGL",
            defenderTag: "#29LY9G2P",
            stars: 1,
            destructionPercentage: 28,
            order: 135,
            duration: 47,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#P0RGRJR8",
          defenderTag: "#908V22VGL",
          stars: 3,
          destructionPercentage: 100,
          order: 138,
          duration: 131,
        },
      },
      {
        tag: "#9RUCVQQVR",
        name: "⭐⭐GUSTAVO⭐⭐",
        townhallLevel: 18,
        mapPosition: 5,
        attacks: [
          {
            attackerTag: "#9RUCVQQVR",
            defenderTag: "#89YUGUQQ",
            stars: 3,
            destructionPercentage: 100,
            order: 61,
            duration: 133,
          },
          {
            attackerTag: "#9RUCVQQVR",
            defenderTag: "#29JPLJQCP",
            stars: 3,
            destructionPercentage: 100,
            order: 65,
            duration: 152,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#UCPC8R0L",
          defenderTag: "#9RUCVQQVR",
          stars: 3,
          destructionPercentage: 100,
          order: 43,
          duration: 159,
        },
      },
      {
        tag: "#2JCCU8YUC",
        name: "LordStark",
        townhallLevel: 18,
        mapPosition: 25,
        attacks: [
          {
            attackerTag: "#2JCCU8YUC",
            defenderTag: "#PGVCLPJG",
            stars: 3,
            destructionPercentage: 100,
            order: 77,
            duration: 101,
          },
          {
            attackerTag: "#2JCCU8YUC",
            defenderTag: "#282RCCLQ",
            stars: 3,
            destructionPercentage: 100,
            order: 79,
            duration: 76,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#PV0UVVR08",
          defenderTag: "#2JCCU8YUC",
          stars: 3,
          destructionPercentage: 100,
          order: 92,
          duration: 174,
        },
      },
      {
        tag: "#2L8RCV88V",
        name: "⭐⭐WashoTuja⭐⭐",
        townhallLevel: 18,
        mapPosition: 14,
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#P9C2VRJ0R",
          defenderTag: "#2L8RCV88V",
          stars: 3,
          destructionPercentage: 100,
          order: 64,
          duration: 131,
        },
      },
      {
        tag: "#2ULYQPCGV",
        name: "Mr Sixto",
        townhallLevel: 18,
        mapPosition: 8,
        attacks: [
          {
            attackerTag: "#2ULYQPCGV",
            defenderTag: "#LC0PQ202J",
            stars: 3,
            destructionPercentage: 100,
            order: 25,
            duration: 148,
          },
          {
            attackerTag: "#2ULYQPCGV",
            defenderTag: "#998V9YJYP",
            stars: 2,
            destructionPercentage: 82,
            order: 27,
            duration: 168,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#PGVCLPJG",
          defenderTag: "#2ULYQPCGV",
          stars: 3,
          destructionPercentage: 100,
          order: 19,
          duration: 147,
        },
      },
      {
        tag: "#RV82802U",
        name: "THE QUEEN",
        townhallLevel: 18,
        mapPosition: 6,
        attacks: [
          {
            attackerTag: "#RV82802U",
            defenderTag: "#GQ0RR2PGL",
            stars: 2,
            destructionPercentage: 77,
            order: 51,
            duration: 123,
          },
          {
            attackerTag: "#RV82802U",
            defenderTag: "#998V9YJYP",
            stars: 1,
            destructionPercentage: 79,
            order: 69,
            duration: 114,
          },
        ],
        opponentAttacks: 3,
        bestOpponentAttack: {
          attackerTag: "#9GG0Y9L28",
          defenderTag: "#RV82802U",
          stars: 3,
          destructionPercentage: 100,
          order: 52,
          duration: 158,
        },
      },
      {
        tag: "#9Y820G0GU",
        name: "ByBlues",
        townhallLevel: 18,
        mapPosition: 45,
        attacks: [
          {
            attackerTag: "#9Y820G0GU",
            defenderTag: "#20PGJPVUC",
            stars: 2,
            destructionPercentage: 88,
            order: 106,
            duration: 142,
          },
          {
            attackerTag: "#9Y820G0GU",
            defenderTag: "#998V9YJYP",
            stars: 3,
            destructionPercentage: 100,
            order: 116,
            duration: 153,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#89YUGUQQ",
          defenderTag: "#9Y820G0GU",
          stars: 3,
          destructionPercentage: 100,
          order: 137,
          duration: 142,
        },
      },
      {
        tag: "#98GQ022RP",
        name: "JEISON",
        townhallLevel: 18,
        mapPosition: 37,
        attacks: [
          {
            attackerTag: "#98GQ022RP",
            defenderTag: "#P8CYY2QV",
            stars: 3,
            destructionPercentage: 100,
            order: 54,
            duration: 178,
          },
          {
            attackerTag: "#98GQ022RP",
            defenderTag: "#PV0UVVR08",
            stars: 2,
            destructionPercentage: 94,
            order: 55,
            duration: 180,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#RC2U2YJR",
          defenderTag: "#98GQ022RP",
          stars: 3,
          destructionPercentage: 100,
          order: 130,
          duration: 136,
        },
      },
      {
        tag: "#2CPY9UVP",
        name: "Algarrovos",
        townhallLevel: 18,
        mapPosition: 7,
        attacks: [
          {
            attackerTag: "#2CPY9UVP",
            defenderTag: "#LGCRRRRCU",
            stars: 2,
            destructionPercentage: 82,
            order: 70,
            duration: 129,
          },
          {
            attackerTag: "#2CPY9UVP",
            defenderTag: "#P0RGRJR8",
            stars: 3,
            destructionPercentage: 100,
            order: 76,
            duration: 169,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#2J9VJ8V80",
          defenderTag: "#2CPY9UVP",
          stars: 3,
          destructionPercentage: 100,
          order: 45,
          duration: 141,
        },
      },
      {
        tag: "#28GC2L8C9",
        name: "Papafrita92",
        townhallLevel: 18,
        mapPosition: 11,
        attacks: [
          {
            attackerTag: "#28GC2L8C9",
            defenderTag: "#Q8LCQL2GG",
            stars: 3,
            destructionPercentage: 100,
            order: 60,
            duration: 101,
          },
          {
            attackerTag: "#28GC2L8C9",
            defenderTag: "#RC2U2YJR",
            stars: 3,
            destructionPercentage: 100,
            order: 62,
            duration: 87,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#Q9CPG8JV2",
          defenderTag: "#28GC2L8C9",
          stars: 3,
          destructionPercentage: 100,
          order: 58,
          duration: 149,
        },
      },
      {
        tag: "#8RL0V8JPY",
        name: "“MARYLAND”",
        townhallLevel: 18,
        mapPosition: 19,
        attacks: [
          {
            attackerTag: "#8RL0V8JPY",
            defenderTag: "#998V9YJYP",
            stars: 2,
            destructionPercentage: 76,
            order: 113,
            duration: 166,
          },
          {
            attackerTag: "#8RL0V8JPY",
            defenderTag: "#UCPC8R0L",
            stars: 2,
            destructionPercentage: 91,
            order: 124,
            duration: 149,
          },
        ],
        opponentAttacks: 3,
        bestOpponentAttack: {
          attackerTag: "#VGUG90RY",
          defenderTag: "#8RL0V8JPY",
          stars: 3,
          destructionPercentage: 100,
          order: 93,
          duration: 165,
        },
      },
      {
        tag: "#LRPJCYL0J",
        name: "**Axiy**",
        townhallLevel: 18,
        mapPosition: 18,
        attacks: [
          {
            attackerTag: "#LRPJCYL0J",
            defenderTag: "#LQLPC002Q",
            stars: 3,
            destructionPercentage: 100,
            order: 56,
            duration: 136,
          },
          {
            attackerTag: "#LRPJCYL0J",
            defenderTag: "#2RQJU0RQG",
            stars: 3,
            destructionPercentage: 100,
            order: 59,
            duration: 166,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#8G2JRLJL",
          defenderTag: "#LRPJCYL0J",
          stars: 3,
          destructionPercentage: 100,
          order: 66,
          duration: 159,
        },
      },
      {
        tag: "#UGJCUGP",
        name: "KING⚡Drummer™️",
        townhallLevel: 18,
        mapPosition: 32,
        attacks: [
          {
            attackerTag: "#UGJCUGP",
            defenderTag: "#20PGJPVUC",
            stars: 3,
            destructionPercentage: 100,
            order: 119,
            duration: 115,
          },
          {
            attackerTag: "#UGJCUGP",
            defenderTag: "#UCPC8R0L",
            stars: 1,
            destructionPercentage: 38,
            order: 122,
            duration: 55,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#222VJ9LCR",
          defenderTag: "#UGJCUGP",
          stars: 3,
          destructionPercentage: 100,
          order: 108,
          duration: 154,
        },
      },
      {
        tag: "#9YGJ9LUPP",
        name: "『NRML』ت Roqueᵘ",
        townhallLevel: 18,
        mapPosition: 33,
        attacks: [
          {
            attackerTag: "#9YGJ9LUPP",
            defenderTag: "#VGUG90RY",
            stars: 3,
            destructionPercentage: 100,
            order: 33,
            duration: 179,
          },
          {
            attackerTag: "#9YGJ9LUPP",
            defenderTag: "#PV0UVVR08",
            stars: 2,
            destructionPercentage: 80,
            order: 34,
            duration: 145,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#P9JVJC2L",
          defenderTag: "#9YGJ9LUPP",
          stars: 3,
          destructionPercentage: 100,
          order: 30,
          duration: 145,
        },
      },
      {
        tag: "#PGVJL0QG2",
        name: "Yurem",
        townhallLevel: 18,
        mapPosition: 35,
        attacks: [
          {
            attackerTag: "#PGVJL0QG2",
            defenderTag: "#YJUY2GCVQ",
            stars: 2,
            destructionPercentage: 98,
            order: 2,
            duration: 180,
          },
          {
            attackerTag: "#PGVJL0QG2",
            defenderTag: "#92P9PJVJ0",
            stars: 3,
            destructionPercentage: 100,
            order: 5,
            duration: 162,
          },
        ],
        opponentAttacks: 3,
        bestOpponentAttack: {
          attackerTag: "#92P9PJVJ0",
          defenderTag: "#PGVJL0QG2",
          stars: 3,
          destructionPercentage: 100,
          order: 132,
          duration: 173,
        },
      },
      {
        tag: "#2LCJP9VU",
        name: '"NRML" Max',
        townhallLevel: 18,
        mapPosition: 31,
        attacks: [
          {
            attackerTag: "#2LCJP9VU",
            defenderTag: "#UY2QUUVQ",
            stars: 2,
            destructionPercentage: 98,
            order: 6,
            duration: 180,
          },
          {
            attackerTag: "#2LCJP9VU",
            defenderTag: "#20PGJPVUC",
            stars: 2,
            destructionPercentage: 96,
            order: 11,
            duration: 154,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#222VJ9LCR",
          defenderTag: "#2LCJP9VU",
          stars: 3,
          destructionPercentage: 100,
          order: 107,
          duration: 151,
        },
      },
      {
        tag: "#2VRVQ9QG",
        name: "Josue",
        townhallLevel: 18,
        mapPosition: 3,
        attacks: [
          {
            attackerTag: "#2VRVQ9QG",
            defenderTag: "#YPLPJ0QPQ",
            stars: 3,
            destructionPercentage: 100,
            order: 10,
            duration: 141,
          },
          {
            attackerTag: "#2VRVQ9QG",
            defenderTag: "#8LUGPRRJY",
            stars: 3,
            destructionPercentage: 100,
            order: 13,
            duration: 176,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#29LY9G2P",
          defenderTag: "#2VRVQ9QG",
          stars: 3,
          destructionPercentage: 100,
          order: 16,
          duration: 159,
        },
      },
      {
        tag: "#89JP8QVJQ",
        name: "Azalrep",
        townhallLevel: 18,
        mapPosition: 34,
        attacks: [
          {
            attackerTag: "#89JP8QVJQ",
            defenderTag: "#LGCRRRRCU",
            stars: 3,
            destructionPercentage: 100,
            order: 71,
            duration: 176,
          },
          {
            attackerTag: "#89JP8QVJQ",
            defenderTag: "#80JYQVYCC",
            stars: 3,
            destructionPercentage: 100,
            order: 73,
            duration: 152,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#Q8LCQL2GG",
          defenderTag: "#89JP8QVJQ",
          stars: 3,
          destructionPercentage: 100,
          order: 111,
          duration: 165,
        },
      },
      {
        tag: "#R9R99QLC",
        name: "LIDER",
        townhallLevel: 18,
        mapPosition: 17,
        opponentAttacks: 3,
        bestOpponentAttack: {
          attackerTag: "#29898CL2Q",
          defenderTag: "#R9R99QLC",
          stars: 3,
          destructionPercentage: 100,
          order: 86,
          duration: 152,
        },
      },
      {
        tag: "#UGJVP9GG",
        name: "TIN ALMENDAREZ",
        townhallLevel: 18,
        mapPosition: 42,
        attacks: [
          {
            attackerTag: "#UGJVP9GG",
            defenderTag: "#GQ0RR2PGL",
            stars: 3,
            destructionPercentage: 100,
            order: 88,
            duration: 131,
          },
          {
            attackerTag: "#UGJVP9GG",
            defenderTag: "#YG9Q8G20",
            stars: 3,
            destructionPercentage: 100,
            order: 90,
            duration: 167,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#2R2YGUCRG",
          defenderTag: "#UGJVP9GG",
          stars: 3,
          destructionPercentage: 100,
          order: 126,
          duration: 174,
        },
      },
      {
        tag: "#YP9PGYGVQ",
        name: "『HW』Ｒｉｇｏ ™️",
        townhallLevel: 18,
        mapPosition: 36,
        attacks: [
          {
            attackerTag: "#YP9PGYGVQ",
            defenderTag: "#CC9J9GRG",
            stars: 2,
            destructionPercentage: 81,
            order: 8,
            duration: 131,
          },
          {
            attackerTag: "#YP9PGYGVQ",
            defenderTag: "#P9C2VRJ0R",
            stars: 2,
            destructionPercentage: 97,
            order: 26,
            duration: 178,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#YQULYPYQU",
          defenderTag: "#YP9PGYGVQ",
          stars: 3,
          destructionPercentage: 100,
          order: 115,
          duration: 149,
        },
      },
      {
        tag: "#289QVP0U2",
        name: "CODY",
        townhallLevel: 18,
        mapPosition: 9,
        attacks: [
          {
            attackerTag: "#289QVP0U2",
            defenderTag: "#9GG0Y9L28",
            stars: 3,
            destructionPercentage: 100,
            order: 37,
            duration: 175,
          },
          {
            attackerTag: "#289QVP0U2",
            defenderTag: "#Q9CPG8JV2",
            stars: 3,
            destructionPercentage: 100,
            order: 39,
            duration: 154,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#9GG0Y9L28",
          defenderTag: "#289QVP0U2",
          stars: 3,
          destructionPercentage: 100,
          order: 53,
          duration: 135,
        },
      },
      {
        tag: "#2GC9QVYPL",
        name: "ƁĄƁĄ/¥ĄGʻĄ502",
        townhallLevel: 18,
        mapPosition: 2,
        attacks: [
          {
            attackerTag: "#2GC9QVYPL",
            defenderTag: "#P8CYY2QV",
            stars: 2,
            destructionPercentage: 65,
            order: 18,
            duration: 173,
          },
          {
            attackerTag: "#2GC9QVYPL",
            defenderTag: "#GVJVGC0P",
            stars: 2,
            destructionPercentage: 80,
            order: 20,
            duration: 151,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#LC0PQ202J",
          defenderTag: "#2GC9QVYPL",
          stars: 3,
          destructionPercentage: 100,
          order: 15,
          duration: 174,
        },
      },
      {
        tag: "#9J9UVP900",
        name: "LordTyrion",
        townhallLevel: 18,
        mapPosition: 23,
        attacks: [
          {
            attackerTag: "#9J9UVP900",
            defenderTag: "#2R2YGUCRG",
            stars: 3,
            destructionPercentage: 100,
            order: 75,
            duration: 89,
          },
          {
            attackerTag: "#9J9UVP900",
            defenderTag: "#29898CL2Q",
            stars: 3,
            destructionPercentage: 100,
            order: 78,
            duration: 112,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#CC9J9GRG",
          defenderTag: "#9J9UVP900",
          stars: 3,
          destructionPercentage: 100,
          order: 95,
          duration: 164,
        },
      },
      {
        tag: "#9GCLY8YU8",
        name: "Captain Kenneth",
        townhallLevel: 18,
        mapPosition: 15,
        attacks: [
          {
            attackerTag: "#9GCLY8YU8",
            defenderTag: "#YQULYPYQU",
            stars: 3,
            destructionPercentage: 100,
            order: 41,
            duration: 163,
          },
          {
            attackerTag: "#9GCLY8YU8",
            defenderTag: "#2J9VJ8V80",
            stars: 3,
            destructionPercentage: 100,
            order: 42,
            duration: 126,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#UY2QUUVQ",
          defenderTag: "#9GCLY8YU8",
          stars: 3,
          destructionPercentage: 100,
          order: 67,
          duration: 147,
        },
      },
      {
        tag: "#8YUVULJCV",
        name: '"NRMAL" Shøah',
        townhallLevel: 18,
        mapPosition: 21,
        attacks: [
          {
            attackerTag: "#8YUVULJCV",
            defenderTag: "#8L8JL90YR",
            stars: 3,
            destructionPercentage: 100,
            order: 103,
            duration: 134,
          },
          {
            attackerTag: "#8YUVULJCV",
            defenderTag: "#YG9Q8G20",
            stars: 2,
            destructionPercentage: 81,
            order: 133,
            duration: 155,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#VV0VLJJ0",
          defenderTag: "#8YUVULJCV",
          stars: 3,
          destructionPercentage: 100,
          order: 104,
          duration: 156,
        },
      },
      {
        tag: "#LQ2V0CQ8",
        name: "⭐⭐rey Mario ⭐⭐",
        townhallLevel: 18,
        mapPosition: 4,
        attacks: [
          {
            attackerTag: "#LQ2V0CQ8",
            defenderTag: "#PV0UVVR08",
            stars: 3,
            destructionPercentage: 100,
            order: 97,
            duration: 164,
          },
          {
            attackerTag: "#LQ2V0CQ8",
            defenderTag: "#GVJVGC0P",
            stars: 3,
            destructionPercentage: 100,
            order: 98,
            duration: 172,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#YJUY2GCVQ",
          defenderTag: "#LQ2V0CQ8",
          stars: 3,
          destructionPercentage: 100,
          order: 28,
          duration: 165,
        },
      },
      {
        tag: "#929GQ92CJ",
        name: "Makine",
        townhallLevel: 18,
        mapPosition: 27,
        attacks: [
          {
            attackerTag: "#929GQ92CJ",
            defenderTag: "#2CC0VRUCL",
            stars: 3,
            destructionPercentage: 100,
            order: 35,
            duration: 129,
          },
          {
            attackerTag: "#929GQ92CJ",
            defenderTag: "#UY2QUUVQ",
            stars: 3,
            destructionPercentage: 100,
            order: 36,
            duration: 88,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#80JYQVYCC",
          defenderTag: "#929GQ92CJ",
          stars: 3,
          destructionPercentage: 100,
          order: 99,
          duration: 141,
        },
      },
      {
        tag: "#PVRJCC99",
        name: "Gu@po 007",
        townhallLevel: 18,
        mapPosition: 43,
        attacks: [
          {
            attackerTag: "#PVRJCC99",
            defenderTag: "#QPP92V90",
            stars: 3,
            destructionPercentage: 100,
            order: 38,
            duration: 98,
          },
          {
            attackerTag: "#PVRJCC99",
            defenderTag: "#YG9Q8G20",
            stars: 2,
            destructionPercentage: 97,
            order: 40,
            duration: 114,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#2RQJU0RQG",
          defenderTag: "#PVRJCC99",
          stars: 3,
          destructionPercentage: 100,
          order: 140,
          duration: 156,
        },
      },
      {
        tag: "#80QQGGCV0",
        name: "raulmg10",
        townhallLevel: 18,
        mapPosition: 41,
        attacks: [
          {
            attackerTag: "#80QQGGCV0",
            defenderTag: "#998V9YJYP",
            stars: 1,
            destructionPercentage: 99,
            order: 101,
            duration: 172,
          },
          {
            attackerTag: "#80QQGGCV0",
            defenderTag: "#8G2JRLJL",
            stars: 3,
            destructionPercentage: 100,
            order: 102,
            duration: 170,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#89YUGUQQ",
          defenderTag: "#80QQGGCV0",
          stars: 3,
          destructionPercentage: 100,
          order: 136,
          duration: 140,
        },
      },
      {
        tag: "#2QG9UP828",
        name: "DrummerGun™️",
        townhallLevel: 18,
        mapPosition: 28,
        attacks: [
          {
            attackerTag: "#2QG9UP828",
            defenderTag: "#UCPC8R0L",
            stars: 1,
            destructionPercentage: 18,
            order: 120,
            duration: 39,
          },
          {
            attackerTag: "#2QG9UP828",
            defenderTag: "#CC9J9GRG",
            stars: 2,
            destructionPercentage: 60,
            order: 121,
            duration: 69,
          },
        ],
        opponentAttacks: 2,
        bestOpponentAttack: {
          attackerTag: "#VGUG90RY",
          defenderTag: "#2QG9UP828",
          stars: 3,
          destructionPercentage: 100,
          order: 109,
          duration: 121,
        },
      },
      {
        tag: "#QUL8Q0VUU",
        name: "ZK yes I'm Bad",
        townhallLevel: 18,
        mapPosition: 1,
        attacks: [
          {
            attackerTag: "#QUL8Q0VUU",
            defenderTag: "#29LY9G2P",
            stars: 3,
            destructionPercentage: 100,
            order: 21,
            duration: 176,
          },
          {
            attackerTag: "#QUL8Q0VUU",
            defenderTag: "#2CC0VRUCL",
            stars: 2,
            destructionPercentage: 99,
            order: 22,
            duration: 180,
          },
        ],
        opponentAttacks: 1,
        bestOpponentAttack: {
          attackerTag: "#LC0PQ202J",
          defenderTag: "#QUL8Q0VUU",
          stars: 3,
          destructionPercentage: 100,
          order: 14,
          duration: 161,
        },
      },
    ],
  },
};
